Add tests for List (Pair 2)
Melkster/voc pull request #39
Opened 2019-09-20 11:06 UTC by rehnarama

Fixes #36 

To run the tests, simply run `make test`

```
Co-authored-by: Adam Inersjö <adam.inersjo.2778@student.uu.se>
Co-authored-by: Joel Westerlund <jowe3751@student.uu.se>
Co-authored-by: Michael Rehn <rehn.michael@outlook.com>
```

2019-09-20 15:36 UTC, JonasNorlinder requested changes

2019-09-20 15:36 UTC, noler commented on python/common/org/python/types/ListTest.java
> -    // Simple stub to test if compilation of tests works
Remove incorrect comment.
```suggestion
```

2019-09-20 15:36 UTC, noler commented on python/common/org/python/types/ListTest.java
> +    public void SetItemString() {
I prefer our (pair 1) naming convention: `methodName_thingToTest`

2019-09-21 21:34 UTC, Melkster commented
Many methods don't test the trivial edge cases like empty lists. I added comments for `__contains__()` and `__add__()`. I think you should also add that edge case for `copy()`, `count()`, `extend()`, `insert()`, `reverse()`, `sort()`.

2019-09-23 15:04 UTC, mawkler approved these changes
Looks good!

2019-09-23 15:06 UTC, merged